name: Golang Build Dagger Github Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: go_build_dagger${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-go-dagger:
    name: Build Go Dagger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: lint --source .
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: build --source .